#define IDB_INFO       2
#define IDB_CLIENT     3
#define IDB_EXIT       4
#define IDB_FACE1     10
#define IDB_CALC      12
#define IDB_CALENDAR  14
#define IDB_ICONEDIT  16

#define ID_NAME      110
#define ID_STREET    120
#define ID_NOTES     130
#define ID_HORBAR    140
#define ID_COUNTRY   150

#define ID_TOP       180
#define ID_PREV      190
#define ID_NEXT      200
#define ID_BOTTOM    210
#define ID_SEARCH    220
#define ID_END         2

#define CLIENTS      100
#define DLG_ABOUT    110
