GENSAMP\GenSamp
c:\util\guias\eh\EHC @CH  -I..\include -O.\EHO -E.\ERR\CH.ERR  -NG -NP
c:\util\guias\eh\EHC @H   -I..\include -O.\EHO -E.\ERR\H.ERR   -NG -NP
c:\util\guias\eh\EHC @TXT -I..\        -O.\EHO -E.\ERR\TXT.ERR -NG -NP
c:\util\guias\eh\EHC @PRG -I..\samples -O.\EHO -E.\ERR\PRG.ERR -NG -NP
c:\util\guias\eh\EHC @REPORT -I..\samples\report -O.\EHO -E.\ERR\PRG.ERR -NG -NP
c:\util\guias\eh\EHC @EHT              -O.\EHO -E.\ERR\EHT.ERR -NG -NP
c:\util\guias\eh\EHC @SAMPLES -I..\samples -O.\EHO -E.\ERR\SAMPLES.ERR -NG -NP
c:\util\guias\eh\EHML fw18.mnu -I.\EHO
o
